version: '3'

services:
  webapiboilerplate.core.tests:
    image: webapiboilerplatecoretests
    build:
      context: .
      dockerfile: Dockerfile
  mssql:
    image: microsoft/mssql-server-linux
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=wiEPzF9pXnuVuejTN3p7
      - MSSQL_PID=Express
    ports: 
      - "1433:1433"
    logging:
      driver: none
