version: '3'

services:
  webapiboilerplate:
    image: webapiboilerplate
    build:
      context: .
      dockerfile: WebApiBoilerplate.WebApi/Dockerfile
  mssql:
    image: microsoft/mssql-server-linux
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=wiEPzF9pXnuVuejTN3p7
      - MSSQL_PID=Express
    ports:
      - 14336:1433
    volumes:
      - db-data:/var/opt/mssql/data
  webapiboilerplate.core.tests:
    image: webapiboilerplatecoretests
    build:
      context: .
      dockerfile: WebApiBoilerplate.Core.Tests/Dockerfile

volumes:
  db-data:

