version: '3.4'

services:
  webapiboilerplate:
    image: ${DOCKER_REGISTRY}webapiboilerplate
    build:
      context: .
      dockerfile: WebApiBoilerplate.WebApi/Dockerfile
  mssql:
    image: microsoft/mssql-server-linux
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "wiEPzF9pXnuVuejTN3p7"
      MSSQL_PID: "Express"
    ports:
      - 14336:1433
    volumes:
      - db-data:/var/opt/mssql/data

volumes:
  db-data:

